[2024-12-29T12:46:03.129+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T12:46:03.143+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_monitor_v1.send_email_alert manual__2024-12-29T12:45:53.474884+00:00 [queued]>
[2024-12-29T12:46:03.150+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_monitor_v1.send_email_alert manual__2024-12-29T12:45:53.474884+00:00 [queued]>
[2024-12-29T12:46:03.152+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-29T12:46:03.163+0000] {taskinstance.py:2889} INFO - Executing <Task(EmailOperator): send_email_alert> on 2024-12-29 12:45:53.474884+00:00
[2024-12-29T12:46:03.169+0000] {standard_task_runner.py:72} INFO - Started process 11295 to run task
[2024-12-29T12:46:03.172+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_monitor_v1', 'send_email_alert', 'manual__2024-12-29T12:45:53.474884+00:00', '--job-id', '1088', '--raw', '--subdir', 'DAGS_FOLDER/email_generation.py', '--cfg-path', '/tmp/tmpz_t_m_br']
[2024-12-29T12:46:03.174+0000] {standard_task_runner.py:105} INFO - Job 1088: Subtask send_email_alert
[2024-12-29T12:46:03.215+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_monitor_v1.send_email_alert manual__2024-12-29T12:45:53.474884+00:00 [running]> on host 95d98a98d27d
[2024-12-29T12:46:03.283+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='stock_price_monitor_v1' AIRFLOW_CTX_TASK_ID='send_email_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T12:45:53.474884+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T12:45:53.474884+00:00'
[2024-12-29T12:46:03.285+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-29T12:46:03.286+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-29T12:46:03.287+0000] {logging_mixin.py:190} INFO - Current task name:send_email_alert state:running start_date:2024-12-29 12:46:03.144899+00:00
[2024-12-29T12:46:03.287+0000] {logging_mixin.py:190} INFO - Dag name:stock_price_monitor_v1 and current dag run status:running
[2024-12-29T12:46:03.288+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T12:46:03.298+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2024-12-29T12:46:03.627+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/operators/smtp.py", line 82, in execute
    with SmtpHook(smtp_conn_id=self.conn_id) as smtp_hook:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/hooks/smtp.py", line 67, in __enter__
    return self.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/hooks/smtp.py", line 89, in get_conn
    self.smtp_client = self._build_client()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/hooks/smtp.py", line 136, in _build_client
    return SMTP(**smtp_kwargs)
  File "/usr/local/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 1057, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)
[2024-12-29T12:46:03.639+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-29T12:46:03.640+0000] {logging_mixin.py:190} INFO - Task start:2024-12-29 12:46:03.144899+00:00 end:2024-12-29 12:46:03.639052+00:00 duration:0.494153
[2024-12-29T12:46:03.641+0000] {logging_mixin.py:190} INFO - Task:<Task(EmailOperator): send_email_alert> dag:<DAG: stock_price_monitor_v1> dagrun:<DagRun stock_price_monitor_v1 @ 2024-12-29 12:45:53.474884+00:00: manual__2024-12-29T12:45:53.474884+00:00, state:running, queued_at: 2024-12-29 12:45:53.526851+00:00. externally triggered: True>
[2024-12-29T12:46:03.642+0000] {logging_mixin.py:190} INFO - Failure caused by [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)
[2024-12-29T12:46:03.643+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_monitor_v1, task_id=send_email_alert, run_id=manual__2024-12-29T12:45:53.474884+00:00, execution_date=20241229T124553, start_date=20241229T124603, end_date=20241229T124603
[2024-12-29T12:46:03.655+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-29T12:46:03.656+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1088 for task send_email_alert ([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007); 11295)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/operators/smtp.py", line 82, in execute
    with SmtpHook(smtp_conn_id=self.conn_id) as smtp_hook:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/hooks/smtp.py", line 67, in __enter__
    return self.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/hooks/smtp.py", line 89, in get_conn
    self.smtp_client = self._build_client()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/smtp/hooks/smtp.py", line 136, in _build_client
    return SMTP(**smtp_kwargs)
  File "/usr/local/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 1057, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)
[2024-12-29T12:46:03.665+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-29T12:46:03.683+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-29T12:46:03.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
