[2024-12-28T12:57:26.754+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T12:57:26.771+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2024-12-27T04:05:00+00:00 [queued]>
[2024-12-28T12:57:26.782+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2024-12-27T04:05:00+00:00 [queued]>
[2024-12-28T12:57:26.784+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-28T12:57:26.799+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2024-12-27 04:05:00+00:00
[2024-12-28T12:57:26.808+0000] {standard_task_runner.py:72} INFO - Started process 26222 to run task
[2024-12-28T12:57:26.812+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'scheduled__2024-12-27T04:05:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmphzmw88e_']
[2024-12-28T12:57:26.815+0000] {standard_task_runner.py:105} INFO - Job 139: Subtask l30_dump_pipeline
[2024-12-28T12:57:26.875+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2024-12-27T04:05:00+00:00 [running]> on host 0a732720d1ba
[2024-12-28T12:57:26.949+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-27T04:05:00+00:00'
[2024-12-28T12:57:26.951+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-28T12:57:26.952+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-28T12:57:26.953+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2024-12-28 12:57:26.772985+00:00
[2024-12-28T12:57:26.954+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2024-12-28T12:57:26.955+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T12:57:54.007+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fbafde67b50>
[2024-12-28T12:57:54.009+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2024-12-28T12:57:54.134+0000] {job.py:229} INFO - Heartbeat recovered after 22.13 seconds
[2024-12-28T12:58:18.419+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2024-12-28T12:58:18.424+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 46281)
[2024-12-28T12:58:18.450+0000] {job.py:229} INFO - Heartbeat recovered after 24.32 seconds
[2024-12-28T12:58:26.376+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 284, in spark_l30d
    # query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 0af5edaa-6922-461f-b7ba-7eab013d84a1, runId = b470d20f-cb85-427f-a537-d02eda808c71] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:58:26.399+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-28T12:58:26.401+0000] {logging_mixin.py:190} INFO - Task start:2024-12-28 12:57:26.772985+00:00 end:2024-12-28 12:58:26.399411+00:00 duration:59.626426
[2024-12-28T12:58:26.402+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2024-12-27 04:05:00+00:00: scheduled__2024-12-27T04:05:00+00:00, state:running, queued_at: 2024-12-28 12:57:23.200317+00:00. externally triggered: False>
[2024-12-28T12:58:26.406+0000] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = 0af5edaa-6922-461f-b7ba-7eab013d84a1, runId = b470d20f-cb85-427f-a537-d02eda808c71] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:58:26.407+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=scheduled__2024-12-27T04:05:00+00:00, execution_date=20241227T040500, start_date=20241228T125726, end_date=20241228T125826
[2024-12-28T12:58:26.436+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T12:58:26.439+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 139 for task l30_dump_pipeline ([STREAM_FAILED] Query [id = 0af5edaa-6922-461f-b7ba-7eab013d84a1, runId = b470d20f-cb85-427f-a537-d02eda808c71] terminated with exception: Failed to create new KafkaAdminClient; 26222)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 284, in spark_l30d
    # query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 0af5edaa-6922-461f-b7ba-7eab013d84a1, runId = b470d20f-cb85-427f-a537-d02eda808c71] terminated with exception: Failed to create new KafkaAdminClient
[2024-12-28T12:58:26.462+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T12:58:26.480+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T12:58:26.483+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
