[2024-12-28T20:21:58.982+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T20:21:58.998+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline_v3.check_status manual__2024-12-28T20:21:56.317928+00:00 [queued]>
[2024-12-28T20:21:59.007+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline_v3.check_status manual__2024-12-28T20:21:56.317928+00:00 [queued]>
[2024-12-28T20:21:59.009+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-28T20:21:59.022+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_status> on 2024-12-28 20:21:56.317928+00:00
[2024-12-28T20:21:59.029+0000] {standard_task_runner.py:72} INFO - Started process 2666 to run task
[2024-12-28T20:21:59.032+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline_v3', 'check_status', 'manual__2024-12-28T20:21:56.317928+00:00', '--job-id', '1012', '--raw', '--subdir', 'DAGS_FOLDER/testing.py', '--cfg-path', '/tmp/tmpnj_1erjz']
[2024-12-28T20:21:59.035+0000] {standard_task_runner.py:105} INFO - Job 1012: Subtask check_status
[2024-12-28T20:21:59.079+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline_v3.check_status manual__2024-12-28T20:21:56.317928+00:00 [running]> on host 95d98a98d27d
[2024-12-28T20:21:59.144+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline_v3' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T20:21:56.317928+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T20:21:56.317928+00:00'
[2024-12-28T20:21:59.147+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-28T20:21:59.148+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-28T20:21:59.149+0000] {logging_mixin.py:190} INFO - Current task name:check_status state:running start_date:2024-12-28 20:21:59.000249+00:00
[2024-12-28T20:21:59.150+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline_v3 and current dag run status:running
[2024-12-28T20:21:59.151+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T20:21:59.161+0000] {logging_mixin.py:190} INFO - None
[2024-12-28T20:21:59.163+0000] {logging_mixin.py:190} INFO - Task 1 failed, not proceeding with task 2
[2024-12-28T20:21:59.164+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testing.py", line 36, in check_status
    raise print('Task 1 failed, not proceeding with task 2')
TypeError: exceptions must derive from BaseException
[2024-12-28T20:21:59.178+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-28T20:21:59.180+0000] {logging_mixin.py:190} INFO - Task start:2024-12-28 20:21:59.000249+00:00 end:2024-12-28 20:21:59.178341+00:00 duration:0.178092
[2024-12-28T20:21:59.182+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): check_status> dag:<DAG: l30d_dump_pipeline_v3> dagrun:<DagRun l30d_dump_pipeline_v3 @ 2024-12-28 20:21:56.317928+00:00: manual__2024-12-28T20:21:56.317928+00:00, state:running, queued_at: 2024-12-28 20:21:56.327750+00:00. externally triggered: True>
[2024-12-28T20:21:59.183+0000] {logging_mixin.py:190} INFO - Failure caused by exceptions must derive from BaseException
[2024-12-28T20:21:59.184+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=l30d_dump_pipeline_v3, task_id=check_status, run_id=manual__2024-12-28T20:21:56.317928+00:00, execution_date=20241228T202156, start_date=20241228T202159, end_date=20241228T202159
[2024-12-28T20:21:59.198+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T20:21:59.200+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1012 for task check_status (exceptions must derive from BaseException; 2666)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testing.py", line 36, in check_status
    raise print('Task 1 failed, not proceeding with task 2')
TypeError: exceptions must derive from BaseException
[2024-12-28T20:21:59.247+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T20:21:59.274+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T20:21:59.277+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
