[2025-01-02T13:06:22.692+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T13:06:22.712+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-01T04:05:00+00:00 [queued]>
[2025-01-02T13:06:22.724+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-01T04:05:00+00:00 [queued]>
[2025-01-02T13:06:22.726+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-02T13:06:22.742+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2025-01-01 04:05:00+00:00
[2025-01-02T13:06:22.753+0000] {standard_task_runner.py:72} INFO - Started process 95701 to run task
[2025-01-02T13:06:22.757+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'scheduled__2025-01-01T04:05:00+00:00', '--job-id', '1657', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmp4x1ix8dk']
[2025-01-02T13:06:22.760+0000] {standard_task_runner.py:105} INFO - Job 1657: Subtask l30_dump_pipeline
[2025-01-02T13:06:22.816+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-01T04:05:00+00:00 [running]> on host 95d98a98d27d
[2025-01-02T13:06:22.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T04:05:00+00:00'
[2025-01-02T13:06:22.905+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-02T13:06:22.906+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-02T13:06:22.908+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2025-01-02 13:06:22.714009+00:00
[2025-01-02T13:06:22.909+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2025-01-02T13:06:22.911+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T13:06:23.179+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fef3078ada0>
[2025-01-02T13:06:23.181+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2025-01-02T13:06:26.892+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-02T13:06:26.894+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-02T13:06:26.895+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-01-02T13:06:30.661+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-02T13:06:30.663+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-02T13:06:30.664+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-02T13:06:30.681+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-02T13:06:30.683+0000] {logging_mixin.py:190} INFO - Task start:2025-01-02 13:06:22.714009+00:00 end:2025-01-02 13:06:30.681115+00:00 duration:7.967106
[2025-01-02T13:06:30.684+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2025-01-01 04:05:00+00:00: scheduled__2025-01-01T04:05:00+00:00, state:running, queued_at: 2025-01-02 13:05:48.572263+00:00. externally triggered: False>
[2025-01-02T13:06:30.685+0000] {logging_mixin.py:190} INFO - Failure caused by NoBrokersAvailable
[2025-01-02T13:06:30.686+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=scheduled__2025-01-01T04:05:00+00:00, execution_date=20250101T040500, start_date=20250102T130622, end_date=20250102T130630
[2025-01-02T13:06:30.702+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T13:06:30.703+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1657 for task l30_dump_pipeline (NoBrokersAvailable; 95701)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-02T13:06:32.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-02T13:06:32.836+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-02T13:06:32.838+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
