[2025-01-02T13:11:33.041+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T13:11:33.060+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-01T04:05:00+00:00 [queued]>
[2025-01-02T13:11:33.071+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-01T04:05:00+00:00 [queued]>
[2025-01-02T13:11:33.073+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-02T13:11:33.088+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2025-01-01 04:05:00+00:00
[2025-01-02T13:11:33.101+0000] {standard_task_runner.py:72} INFO - Started process 96235 to run task
[2025-01-02T13:11:33.104+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'scheduled__2025-01-01T04:05:00+00:00', '--job-id', '1664', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmpoeno7usu']
[2025-01-02T13:11:33.107+0000] {standard_task_runner.py:105} INFO - Job 1664: Subtask l30_dump_pipeline
[2025-01-02T13:11:33.161+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-01T04:05:00+00:00 [running]> on host 95d98a98d27d
[2025-01-02T13:11:33.243+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T04:05:00+00:00'
[2025-01-02T13:11:33.245+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-02T13:11:33.247+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-02T13:11:33.248+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2025-01-02 13:11:33.062026+00:00
[2025-01-02T13:11:33.249+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2025-01-02T13:11:33.250+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T13:11:41.933+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fef307be1d0>
[2025-01-02T13:11:41.940+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2025-01-02T13:11:45.677+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-02T13:11:45.679+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-02T13:11:45.680+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-01-02T13:11:49.400+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-02T13:11:49.401+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-02T13:11:49.407+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-02T13:11:49.445+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-02T13:11:49.447+0000] {logging_mixin.py:190} INFO - Task start:2025-01-02 13:11:33.062026+00:00 end:2025-01-02 13:11:49.441660+00:00 duration:16.379634
[2025-01-02T13:11:49.449+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2025-01-01 04:05:00+00:00: scheduled__2025-01-01T04:05:00+00:00, state:running, queued_at: 2025-01-02 13:05:48.572263+00:00. externally triggered: False>
[2025-01-02T13:11:49.449+0000] {logging_mixin.py:190} INFO - Failure caused by NoBrokersAvailable
[2025-01-02T13:11:49.450+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=scheduled__2025-01-01T04:05:00+00:00, execution_date=20250101T040500, start_date=20250102T131133, end_date=20250102T131149
[2025-01-02T13:11:49.484+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T13:11:49.486+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1664 for task l30_dump_pipeline (NoBrokersAvailable; 96235)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-02T13:11:49.545+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-02T13:11:49.568+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-02T13:11:49.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
