[2025-01-03T18:53:50.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-03T18:53:50.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-02T04:05:00+00:00 [queued]>
[2025-01-03T18:53:50.052+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-02T04:05:00+00:00 [queued]>
[2025-01-03T18:53:50.054+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-03T18:53:50.068+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2025-01-02 04:05:00+00:00
[2025-01-03T18:53:50.076+0000] {standard_task_runner.py:72} INFO - Started process 1890 to run task
[2025-01-03T18:53:50.081+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'scheduled__2025-01-02T04:05:00+00:00', '--job-id', '1921', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmpkllao66b']
[2025-01-03T18:53:50.085+0000] {standard_task_runner.py:105} INFO - Job 1921: Subtask l30_dump_pipeline
[2025-01-03T18:53:50.144+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2025-01-02T04:05:00+00:00 [running]> on host 95d98a98d27d
[2025-01-03T18:53:50.229+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T04:05:00+00:00'
[2025-01-03T18:53:50.232+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-03T18:53:50.233+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-03T18:53:50.234+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2025-01-03 18:53:50.044069+00:00
[2025-01-03T18:53:50.235+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2025-01-03T18:53:50.236+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-03T18:53:54.991+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fef30776650>
[2025-01-03T18:53:54.992+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2025-01-03T18:53:58.702+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-03T18:53:58.704+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-03T18:53:58.706+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-01-03T18:54:02.417+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-03T18:54:02.419+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-03T18:54:02.421+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-03T18:54:02.434+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-03T18:54:02.436+0000] {logging_mixin.py:190} INFO - Task start:2025-01-03 18:53:50.044069+00:00 end:2025-01-03 18:54:02.433746+00:00 duration:12.389677
[2025-01-03T18:54:02.437+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2025-01-02 04:05:00+00:00: scheduled__2025-01-02T04:05:00+00:00, state:running, queued_at: 2025-01-03 18:47:55.304725+00:00. externally triggered: False>
[2025-01-03T18:54:02.439+0000] {logging_mixin.py:190} INFO - Failure caused by NoBrokersAvailable
[2025-01-03T18:54:02.440+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=scheduled__2025-01-02T04:05:00+00:00, execution_date=20250102T040500, start_date=20250103T185350, end_date=20250103T185402
[2025-01-03T18:54:02.455+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-03T18:54:02.456+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1921 for task l30_dump_pipeline (NoBrokersAvailable; 1890)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-03T18:54:02.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-03T18:54:02.512+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-03T18:54:02.516+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
