[2025-01-01T18:24:54.353+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T18:24:54.370+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2024-12-31T04:05:00+00:00 [queued]>
[2025-01-01T18:24:54.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2024-12-31T04:05:00+00:00 [queued]>
[2025-01-01T18:24:54.383+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-01T18:24:54.396+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): l30_dump_pipeline> on 2024-12-31 04:05:00+00:00
[2025-01-01T18:24:54.406+0000] {standard_task_runner.py:72} INFO - Started process 91802 to run task
[2025-01-01T18:24:54.411+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'l30_dump_pipeline', 'scheduled__2024-12-31T04:05:00+00:00', '--job-id', '1489', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmpg6egzhsu']
[2025-01-01T18:24:54.414+0000] {standard_task_runner.py:105} INFO - Job 1489: Subtask l30_dump_pipeline
[2025-01-01T18:24:54.463+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.l30_dump_pipeline scheduled__2024-12-31T04:05:00+00:00 [running]> on host 95d98a98d27d
[2025-01-01T18:24:54.536+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='l30_dump_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-31T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-31T04:05:00+00:00'
[2025-01-01T18:24:54.538+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T18:24:54.540+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T18:24:54.541+0000] {logging_mixin.py:190} INFO - Current task name:l30_dump_pipeline state:running start_date:2025-01-01 18:24:54.372333+00:00
[2025-01-01T18:24:54.542+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2025-01-01T18:24:54.543+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T18:25:00.201+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fef307cd630>
[2025-01-01T18:25:00.202+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2025-01-01T18:25:03.934+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-01T18:25:03.935+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-01T18:25:03.936+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-01-01T18:25:07.644+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-01-01T18:25:07.645+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2025-01-01T18:25:07.646+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-01T18:25:07.658+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T18:25:07.659+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 18:24:54.372333+00:00 end:2025-01-01 18:25:07.657956+00:00 duration:13.285623
[2025-01-01T18:25:07.661+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): l30_dump_pipeline> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2024-12-31 04:05:00+00:00: scheduled__2024-12-31T04:05:00+00:00, state:running, queued_at: 2025-01-01 18:18:33.758290+00:00. externally triggered: False>
[2025-01-01T18:25:07.662+0000] {logging_mixin.py:190} INFO - Failure caused by NoBrokersAvailable
[2025-01-01T18:25:07.662+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=l30d_dump_pipeline, task_id=l30_dump_pipeline, run_id=scheduled__2024-12-31T04:05:00+00:00, execution_date=20241231T040500, start_date=20250101T182454, end_date=20250101T182507
[2025-01-01T18:25:07.674+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T18:25:07.676+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1489 for task l30_dump_pipeline (NoBrokersAvailable; 91802)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 15, in l30d_data_dump_pipeline
    spark_l30d(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 195, in spark_l30d
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-01-01T18:25:07.721+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T18:25:07.735+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T18:25:07.738+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
