[2024-12-29T09:27:10.187+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T09:27:10.208+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: l30d_dump_pipeline.check_status scheduled__2024-12-28T04:05:00+00:00 [queued]>
[2024-12-29T09:27:10.218+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: l30d_dump_pipeline.check_status scheduled__2024-12-28T04:05:00+00:00 [queued]>
[2024-12-29T09:27:10.220+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-29T09:27:10.233+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_status> on 2024-12-28 04:05:00+00:00
[2024-12-29T09:27:10.251+0000] {standard_task_runner.py:72} INFO - Started process 4018 to run task
[2024-12-29T09:27:10.256+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'l30d_dump_pipeline', 'check_status', 'scheduled__2024-12-28T04:05:00+00:00', '--job-id', '1027', '--raw', '--subdir', 'DAGS_FOLDER/L30D_data_dump.py', '--cfg-path', '/tmp/tmpt6f7799r']
[2024-12-29T09:27:10.259+0000] {standard_task_runner.py:105} INFO - Job 1027: Subtask check_status
[2024-12-29T09:27:10.321+0000] {task_command.py:467} INFO - Running <TaskInstance: l30d_dump_pipeline.check_status scheduled__2024-12-28T04:05:00+00:00 [running]> on host 95d98a98d27d
[2024-12-29T09:27:10.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='l30d_dump_pipeline' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T04:05:00+00:00'
[2024-12-29T09:27:10.418+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-29T09:27:10.419+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-29T09:27:10.422+0000] {logging_mixin.py:190} INFO - Current task name:check_status state:running start_date:2024-12-29 09:27:10.209977+00:00
[2024-12-29T09:27:10.425+0000] {logging_mixin.py:190} INFO - Dag name:l30d_dump_pipeline and current dag run status:running
[2024-12-29T09:27:10.427+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T09:27:10.447+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/L30D_data_dump.py", line 45, in check_status
    raise Exception('Could not retrieve status from previous DAG')
Exception: Could not retrieve status from previous DAG
[2024-12-29T09:27:10.468+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-29T09:27:10.474+0000] {logging_mixin.py:190} INFO - Task start:2024-12-29 09:27:10.209977+00:00 end:2024-12-29 09:27:10.468030+00:00 duration:0.258053
[2024-12-29T09:27:10.475+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): check_status> dag:<DAG: l30d_dump_pipeline> dagrun:<DagRun l30d_dump_pipeline @ 2024-12-28 04:05:00+00:00: scheduled__2024-12-28T04:05:00+00:00, state:running, queued_at: 2024-12-29 09:26:56.707323+00:00. externally triggered: False>
[2024-12-29T09:27:10.477+0000] {logging_mixin.py:190} INFO - Failure caused by Could not retrieve status from previous DAG
[2024-12-29T09:27:10.478+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=l30d_dump_pipeline, task_id=check_status, run_id=scheduled__2024-12-28T04:05:00+00:00, execution_date=20241228T040500, start_date=20241229T092710, end_date=20241229T092710
[2024-12-29T09:27:10.500+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-29T09:27:10.502+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1027 for task check_status (Could not retrieve status from previous DAG; 4018)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/L30D_data_dump.py", line 45, in check_status
    raise Exception('Could not retrieve status from previous DAG')
Exception: Could not retrieve status from previous DAG
[2024-12-29T09:27:10.549+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-29T09:27:10.570+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-29T09:27:10.573+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
